import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

# ── Load data ─────────────────────────────────────────────────
df = pd.read_csv('/home/tajbid/stm32-workspace/projects/08_adc/dataset3f_clean.csv')
X = df[['range', 'std']].values.astype(np.float32)
y = df['label'].values

print(f"Samples: {len(y)} ({sum(y==0)} normal, {sum(y==1)} anomaly)")
print(f"\nFeature stats:")
print(df[['range', 'mean', 'std']].describe())

# ── Normalize ─────────────────────────────────────────────────
X_mean = X.mean(axis=0)
X_std  = X.std(axis=0)
X_norm = (X - X_mean) / X_std

print(f"\nX_mean: {X_mean}")
print(f"X_std:  {X_std}")

# ── Split ─────────────────────────────────────────────────────
X_train, X_test, y_train, y_test = train_test_split(
    X_norm, y, test_size=0.2, random_state=42)

# ── Train ─────────────────────────────────────────────────────
model = LogisticRegression(max_iter=1000, class_weight='balanced')
model.fit(X_train, y_train)

# ── Evaluate ──────────────────────────────────────────────────
y_pred = model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
cm  = confusion_matrix(y_test, y_pred)

print(f"\nAccuracy: {acc*100:.1f}%")
print(f"Confusion matrix:\n{cm}")

# ── Extract weights ───────────────────────────────────────────
w = model.coef_[0]        # shape (3,)
b = model.intercept_[0]

print(f"\nWeights: {w}")
print(f"Bias:    {b:.6f}")

# ── Generate C header ─────────────────────────────────────────
# ── Generate C header ─────────────────────────────────────────
lines = [
    "// Auto-generated by train_lr.py",
    "// Logistic Regression — 3 features: range, mean, std",
    "",
    "#ifndef LR_MODEL_H",
    "#define LR_MODEL_H",
    "",
    f"#define LR_W0      {w[0]:.6f}f   // range weight",
    #f"#define LR_W1      {w[1]:.6f}f   // mean weight",
    f"#define LR_W2      {w[1]:.6f}f   // std weight",
    f"#define LR_BIAS    {b:.6f}f",
    "",
    f"#define LR_MEAN0   {X_mean[0]:.6f}f  // range mean",
    #f"#define LR_MEAN1   {X_mean[1]:.6f}f  // mean mean",
    f"#define LR_MEAN2   {X_mean[1]:.6f}f  // std mean",
    "",
    f"#define LR_STD0    {X_std[0]:.6f}f   // range std",
    #f"#define LR_STD1    {X_std[1]:.6f}f   // mean std",
    f"#define LR_STD2    {X_std[1]:.6f}f   // std std",
    "",
    "#endif",
]

with open('/home/tajbid/stm32-workspace/projects/08_adc/include/lr_model.h', 'w') as f:
    f.write('\n'.join(lines))

print("\nGenerated: include/lr_model.h")