import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import tensorflow as tf

# ── Load data ─────────────────────────────────────────────────
df = pd.read_csv('/home/tajbid/stm32-workspace/projects/08_adc/dataset3f_clean.csv')
X = df[['range', 'std']].values.astype(np.float32)
y = df['label'].values.astype(np.float32)

# ── Normalize ─────────────────────────────────────────────────
X_mean = X.mean(axis=0)
X_std  = X.std(axis=0)
X_norm = (X - X_mean) / X_std

print(f"Samples: {len(y)} ({int(sum(y==0))} normal, {int(sum(y==1))} anomaly)")
print(f"X_mean: {X_mean}")
print(f"X_std:  {X_std}")

# ── Split ─────────────────────────────────────────────────────
X_train, X_test, y_train, y_test = train_test_split(
    X_norm, y, test_size=0.2, random_state=42)

# ── Build model ───────────────────────────────────────────────
model = tf.keras.Sequential([
    tf.keras.layers.Dense(8, activation='relu', input_shape=(2,)),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

# ── Train ─────────────────────────────────────────────────────
history = model.fit(
    X_train, y_train,
    epochs=100,
    batch_size=32,
    validation_data=(X_test, y_test),
    verbose=1
)

# ── Evaluate ──────────────────────────────────────────────────
y_pred = (model.predict(X_test) >= 0.5).astype(int).flatten()
acc = accuracy_score(y_test, y_pred)
cm  = confusion_matrix(y_test, y_pred)

print(f"\nAccuracy: {acc*100:.1f}%")
print(f"Confusion matrix:\n{cm}")

# ── Extract weights ───────────────────────────────────────────
W1 = model.layers[0].get_weights()[0]  # shape (2, 8)
b1 = model.layers[0].get_weights()[1]  # shape (8,)
W2 = model.layers[1].get_weights()[0]  # shape (8, 1)
b2 = model.layers[1].get_weights()[1]  # shape (1,)

print(f"\nW1 shape: {W1.shape}")
print(f"b1 shape: {b1.shape}")
print(f"W2 shape: {W2.shape}")
print(f"b2 shape: {b2.shape}")

# ── Generate C header ─────────────────────────────────────────
def fmt(arr):
    return ', '.join([f'{v:.6f}f' for v in arr.flatten()])

lines = [
    "// Auto-generated by train_nn.py",
    "// Neural Network: Dense(2->8 ReLU) -> Dense(8->1 Sigmoid)",
    "",
    "#ifndef NN_MODEL_H",
    "#define NN_MODEL_H",
    "",
    f"#define NN_MEAN0   {X_mean[0]:.6f}f",
    f"#define NN_MEAN1   {X_mean[1]:.6f}f",
    f"#define NN_STD0    {X_std[0]:.6f}f",
    f"#define NN_STD1    {X_std[1]:.6f}f",
    "",
    "// W1[2][8] — input to hidden",
    f"static const float NN_W1[2][8] = {{",
    f"    {{{fmt(W1[0])}}},",
    f"    {{{fmt(W1[1])}}}",
    f"}};",
    "",
    "// b1[8] — hidden bias",
    f"static const float NN_B1[8] = {{{fmt(b1)}}};",
    "",
    "// W2[8] — hidden to output",
    f"static const float NN_W2[8] = {{{fmt(W2.flatten())}}};",
    "",
    "// b2 — output bias",
    f"#define NN_B2      {b2[0]:.6f}f",
    "",
    "#endif",
]

with open('/home/tajbid/stm32-workspace/projects/08_adc/include/nn_model.h', 'w') as f:
    f.write('\n'.join(lines))

print("\nGenerated: include/nn_model.h")