// Auto-generated by train_lr.py
// Logistic Regression — 3 features: range, mean, std

#ifndef LR_MODEL_H
#define LR_MODEL_H

#define LR_W0      4.484238f   // range weight
#define LR_W2      1.977449f   // std weight
#define LR_BIAS    3.316162f

#define LR_MEAN0   21583.699219f  // range mean
#define LR_MEAN2   7169.398438f  // std mean

#define LR_STD0    28458.375000f   // range std
#define LR_STD2    10270.968750f   // std std

#endif