// Auto-generated by train_nn.py
// Neural Network: Dense(2->8 ReLU) -> Dense(8->1 Sigmoid)

#ifndef NN_MODEL_H
#define NN_MODEL_H

#define NN_MEAN0   21583.699219f
#define NN_MEAN1   7169.398438f
#define NN_STD0    28458.375000f
#define NN_STD1    10270.968750f

// W1[2][8] — input to hidden
static const float NN_W1[2][8] = {
    {0.019208f, 0.395536f, -0.235287f, 1.021318f, 0.083888f, 0.111904f, 0.235372f, -1.498043f},
    {-0.100882f, -0.084819f, 0.136401f, 0.777925f, 0.051139f, 0.357300f, 0.967119f, -1.267882f}
};

// b1[8] — hidden bias
static const float NN_B1[8] = {-0.077668f, -0.278776f, -0.104112f, 1.323568f, -0.221385f, -0.322825f, 0.858953f, 0.358415f};

// W2[8] — hidden to output
static const float NN_W2[8] = {0.743004f, -0.069716f, 0.516689f, 1.107789f, -0.185140f, -0.409646f, 1.681032f, -0.610185f};

// b2 — output bias
#define NN_B2      0.027075f

#endif